import { pad, ts } from '../utils';

/**
 * Removes empty lines and indent by two spaces to match the rest of the file.
 */
function normalizeLines(code: string) {
  return (
    code
      .split('\n')
      // FIXME: the code should be cleaned up by the codegen functions. Removing empty lines here
      // reduces readability of the route file info map.
      .filter((line) => line.length !== 0)
      .map((line) => pad(2, line))
      .join('\n')
  );
}

export function generateDTS({
  routeNamedMap,
  routeTreeMap,
  routeFileInfoMap,
  paramsTypesDeclaration,
  customParamsType,
}: {
  routeNamedMap: string;
  routeTreeMap: string;
  routeFileInfoMap: string;
  paramsTypesDeclaration: string;
  customParamsType: string;
}) {
  return ts`
/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by essor-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

${
  paramsTypesDeclaration
    ? `
// Custom route params parsers
${paramsTypesDeclaration}

`.trimStart()
    : ''
}
declare module 'essor-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
    RouteRecordRaw,
  } from 'essor-router'
  import type {
    InferRouteBeforeLoadData,
    InferRouteDefinitionFromDefinePageModule,
    InferRouteLoaderData,
    InferRouteSearch,
    InferRouteStartOptions,
    RouteTreeNodeInfo,
  } from 'essor-router/experimental'

  interface TypesConfig {
    ParamParsers: ${customParamsType}
  }

  /**
   * Route name map generated by essor-router
   */
${normalizeLines(routeNamedMap)}

  /**
   * Route tree map generated by essor-router.
   * Includes search/loader/start type inference from defineRoute()/definePage().
   */
${normalizeLines(routeTreeMap)}

  export type RouteTreeNames = keyof RouteTreeMap

  /**
   * Route file to route info map by essor-router.
   * Used by the \`typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
${normalizeLines(routeFileInfoMap)}

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap

  export declare const routes: RouteRecordRaw[]
}

declare module 'essor-router/auto-resolver' {
  export const resolver: any
}
`.trimStart();
}
