import { nextTick, provide, shallowSignal, toRaw } from 'essor';
import { isFunction, isObject, isString } from '@estjs/shared';
import { assign, isBrowser, noop } from '../utils';
import {
  type NavigationGuardWithThis,
  type NavigationHookAfter,
  type RouteLocation,
  type RouteLocationNormalized,
  type RouteLocationNormalizedLoaded,
  type RouteLocationRawTyped,
  type RouteRecordName,
  type RouteRecordRaw,
  START_LOCATION_NORMALIZED,
} from '../types';
import { createRouterMatcher } from '../matcher';
import { createWebHistory } from '../history/html5';
import { createWebHashHistory } from '../history/hash';
import { createMemoryHistory } from '../history/memory';
import {
  type ErrorListener,
  type MatcherResolver,
  createNavigator,
  createReactiveRoute,
} from '../navigation/navigator';
import { NavigationType, type RouterHistory } from '../history/common';
import { registerActiveRouter, unregisterActiveRouter } from './useApi';
import { routeLocationKey, routerKey, routerViewLocationKey } from './injectionSymbols';
import {
  type RouterScrollBehavior,
  type _ScrollPositionNormalized,
  computeScrollPosition,
  createScrollPositionStore,
  getScrollKey,
  scrollToPosition,
} from './scrollBehavior';
import {
  ErrorTypes,
  type NavigationFailure,
  type NavigationRedirectError,
  isNavigationFailure,
} from './errors';
import { parseQuery as defaultParseQuery, stringifyQuery as defaultStringifyQuery } from './query';
import { warn } from './warning';
import type { Signal } from 'essor';
import type { RouteRecord } from '../matcher/types';
import type { RouteRecordMatcher } from '../matcher/pathMatcher';
import type { PathParserOptions } from '../matcher/pathParserRanker';
import type { FixedRouteResolver } from '../fixedResolver';

export type { ErrorListener, ErrorListener as _ErrorListener };

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type History = 'history' | 'hash' | 'memory';

export interface RouterOptions extends PathParserOptions {
  /**
   * Base URL used by string history modes and generated hrefs.
   */
  base?: string;

  /**
   * History implementation or shorthand mode. Use `memory` for tests and SSR.
   */
  history: History | RouterHistory;

  /**
   * Initial route records registered when the router is created. May be omitted
   * when `resolver` is provided, but then runtime route APIs only know about
   * routes added through those APIs.
   */
  routes?: Readonly<RouteRecordRaw[]>;

  /**
   * Prebuilt resolver generated by `unplugin-essor-router`. When supplied, it
   * resolves navigation until runtime routes are mutated. After
   * `addRoute`/`removeRoute`/`clearRoutes`, the runtime matcher is consulted
   * first so dynamic route APIs stay consistent.
   */
  resolver?: FixedRouteResolver;

  /**
   * Optional scroll handler called after successful navigations in the browser.
   */
  scrollBehavior?: RouterScrollBehavior;

  /**
   * Custom query parser. Receives the raw search string without the leading `?`.
   */
  parseQuery?: (search: string) => any;

  /**
   * Custom query stringifier. Must return a string without the leading `?`.
   */
  stringifyQuery?: (query: any) => string;

  /**
   * Class applied by RouterLink when the target route is active.
   */
  linkActiveClass?: string;

  /**
   * Class applied by RouterLink when the target route exactly matches.
   */
  linkExactActiveClass?: string;
}

export interface Router {
  /**
   * Reactive current route. It is updated only after a navigation is committed.
   */
  readonly currentRoute: Signal<RouteLocationNormalizedLoaded>;

  /**
   * Normalized router options passed to `createRouter`.
   */
  readonly options: RouterOptions;

  /**
   * Whether the router listens to history changes.
   */
  listening: boolean;

  addRoute(parentName: RouteRecordName, route: RouteRecordRaw): () => void;
  addRoute(route: RouteRecordRaw): () => void;
  removeRoute(name: RouteRecordName): void;
  hasRoute(name: RouteRecordName): boolean;
  getRoutes(): RouteRecord[];
  clearRoutes(): void;

  resolve(
    to: RouteLocationRawTyped,
    currentLocation?: RouteLocationNormalizedLoaded,
  ): RouteLocation & { href: string };

  push(to: RouteLocationRawTyped): Promise<NavigationFailure | void | undefined>;
  replace(to: RouteLocationRawTyped): Promise<NavigationFailure | void | undefined>;

  /**
   * Preloads async route components and route data hooks for a target location.
   */
  preloadRoute(to: RouteLocationRawTyped): Promise<RouteLocationNormalizedLoaded>;

  back(): ReturnType<Router['go']>;
  forward(): ReturnType<Router['go']>;
  go(delta: number): void;

  beforeEach(guard: NavigationGuardWithThis<undefined>): () => void;
  beforeResolve(guard: NavigationGuardWithThis<undefined>): () => void;
  afterEach(guard: NavigationHookAfter): () => void;

  onError(handler: ErrorListener): () => void;
  isReady(): Promise<void>;
  init(): void;
  destroy(): void;

  getPrerenderPaths(): PrerenderPathInfo[];
  getPrerenderPathsAsync(): Promise<PrerenderPathInfo[]>;
  getRouteRenderMode(name: RouteRecordName): RouteRenderMode;
}

/**
 * Extended router shape used by build tooling for HMR. Not exported from the
 * public package — consumers obtain it via type assertion.
 *
 * @internal
 */
export interface _RouterInternal extends Router {
  /**
   * Replaces the prebuilt resolver during HMR.
   *
   * @internal
   */
  _hmrReplaceResolver(resolver: FixedRouteResolver): void;
  /**
   * Replaces generated route records during HMR.
   *
   * @internal
   */
  _hmrReplaceRoutes(routes: Readonly<RouteRecordRaw[]>): void;
}

export type RouteRenderMode = 'csr' | 'ssr' | 'prerender';

export interface PrerenderPathInfo {
  name: string | symbol | undefined;
  pathTemplate: string;
  paths: string[];
  meta: Record<string | number | symbol, any>;
}

// ---------------------------------------------------------------------------
// History factory
// ---------------------------------------------------------------------------

export function createHistory(mode: History | RouterHistory, base?: string): RouterHistory {
  if (isObject(mode)) return mode as RouterHistory;
  switch (mode) {
    case 'history':
      return createWebHistory(base);
    case 'hash':
      return createWebHashHistory(base);
    case 'memory':
      return createMemoryHistory(base);
    default:
      throw new Error('Invalid history mode');
  }
}

// ---------------------------------------------------------------------------
// Tree traversal helper (simplifies record tracking)
// ---------------------------------------------------------------------------

function forEachInTree(m: RouteRecordMatcher, fn: (m: RouteRecordMatcher) => void) {
  fn(m);
  for (const child of m.children) forEachInTree(child, fn);
  for (const alias of m.alias) forEachInTree(alias, fn);
}

// ---------------------------------------------------------------------------
// Router factory
// ---------------------------------------------------------------------------

export function createRouter(options: RouterOptions): Router {
  // --- Core infrastructure ---
  const matcher = createRouterMatcher(options.routes || [], options);
  let activeResolver = options.resolver;
  // Keep the fixed resolver from resolving generated records that runtime APIs
  // have explicitly removed, while still supporting resolver-only routers.
  let allowResolverOnlyRecords = !options.routes?.length;
  const activeGeneratedRouteNames = new Set<RouteRecordName>();
  const activeGeneratedRoutePaths = new Set<string>();
  const runtimeRouteRecords = new Set<RouteRecord>();

  // Seed the generated record trackers with the initial routes
  for (const m of matcher.getRoutes()) {
    trackRecord(m.record);
  }

  const parseQuery = options.parseQuery || defaultParseQuery;
  const stringifyQuery = options.stringifyQuery || defaultStringifyQuery;

  const routerHistory: RouterHistory = isString(options.history)
    ? createHistory(options.history, options.base)
    : (options.history as RouterHistory);

  const currentRoute = shallowSignal<RouteLocationNormalizedLoaded>(START_LOCATION_NORMALIZED);
  const routeLocationContext = createReactiveRoute(currentRoute);
  const scrollPositionStore = createScrollPositionStore();

  // --- Scroll handling ---
  const handleScroll = (
    to: RouteLocationNormalizedLoaded,
    from: RouteLocationNormalizedLoaded,
    isPush: boolean,
    isFirstNavigation: boolean,
    delta = 0,
  ): Promise<unknown> => {
    const { scrollBehavior } = options;
    if (!isBrowser || !scrollBehavior) return Promise.resolve();

    const scrollPosition: _ScrollPositionNormalized | null =
      (!isPush && scrollPositionStore.get(getScrollKey(from.fullPath, delta))) ||
      ((isFirstNavigation || !isPush) &&
        routerHistory.state &&
        (routerHistory.state as any).scroll) ||
      null;

    return Promise.resolve()
      .then(() => scrollBehavior(to, from, scrollPosition))
      .then((position) => position && scrollToPosition(position))
      .catch((error) => {
        if (__DEV__) warn('Error while handling scroll behavior:', error);
      });
  };

  // --- Navigator (resolution + guards + navigation + readiness) ---
  const nav = createNavigator({
    matcher: {
      resolve(location, currentLocation) {
        return resolveWithActiveMatcher(location, currentLocation);
      },
    },
    routerHistory,
    currentRoute,
    parseQuery,
    stringifyQuery,
    handleScroll,
  });

  // --- Route resolution with resolver/matcher priority ---

  function resolveWithActiveMatcher(
    location: Parameters<MatcherResolver['resolve']>[0],
    currentLocation: Parameters<MatcherResolver['resolve']>[1],
  ) {
    if (!activeResolver) {
      return matcher.resolve(location, currentLocation);
    }

    if ('name' in location && location.name) {
      const recordMatcher = matcher.getRecordMatcher(location.name);
      if (recordMatcher && runtimeRouteRecords.has(recordMatcher.record)) {
        return matcher.resolve(location, currentLocation);
      }
      const resolved = activeResolver.resolve(location, currentLocation);
      return hasActiveGeneratedMatch(resolved.matched)
        ? resolved
        : matcher.resolve(location, currentLocation);
    }

    if (location.path != null) {
      const runtimeResolved = matcher.resolve(location, currentLocation);
      if (usesRuntimeRecord(runtimeResolved.matched)) {
        return runtimeResolved;
      }

      const resolved = activeResolver.resolve(location, currentLocation);
      return resolved.matched.length === 0 || hasActiveGeneratedMatch(resolved.matched)
        ? resolved
        : runtimeResolved;
    }

    if (usesRuntimeRecord(currentLocation.matched)) {
      return matcher.resolve(location, currentLocation);
    }

    const resolved = activeResolver.resolve(location, currentLocation);
    return resolved.matched.length === 0 || hasActiveGeneratedMatch(resolved.matched)
      ? resolved
      : matcher.resolve(location, currentLocation);
  }

  function usesRuntimeRecord(records: readonly RouteRecord[]) {
    return records.some((record) => runtimeRouteRecords.has(record));
  }

  function hasActiveGeneratedMatch(records: readonly RouteRecord[]) {
    const record = records.at(-1);
    if (!record) return false;
    if (allowResolverOnlyRecords) return true;
    return record.name
      ? activeGeneratedRouteNames.has(record.name)
      : activeGeneratedRoutePaths.has(record.path);
  }

  // --- Record tracking (simplified) ---

  function trackRecord(record: RouteRecord) {
    if (record.name) {
      activeGeneratedRouteNames.add(record.name);
    } else {
      activeGeneratedRoutePaths.add(record.path);
    }
  }

  function untrackRecord(record: RouteRecord) {
    if (record.name) {
      activeGeneratedRouteNames.delete(record.name);
    } else {
      activeGeneratedRoutePaths.delete(record.path);
    }
  }

  // --- Route management ---

  function addRoute(parentOrRoute: RouteRecordName | RouteRecordRaw, route?: RouteRecordRaw) {
    let parentMatcher;
    if (route) {
      parentMatcher = matcher.getRecordMatcher(parentOrRoute as RouteRecordName);
      if (!parentMatcher) {
        if (__DEV__)
          warn(`Parent route "${String(parentOrRoute)}" not found when adding child route`);
        return () => {};
      }
    }

    const previousMatchers = new Set(matcher.getRoutes());
    const remove = matcher.addRoute((route || parentOrRoute) as RouteRecordRaw, parentMatcher);

    // Mark newly added matchers as runtime records
    const addedRecords: RouteRecord[] = [];
    for (const m of matcher.getRoutes()) {
      if (!previousMatchers.has(m)) {
        runtimeRouteRecords.add(m.record);
        addedRecords.push(m.record);
      }
    }
    // Clean up matchers that were removed as a side effect (e.g. name collision)
    for (const m of previousMatchers) {
      if (!matcher.getRoutes().includes(m)) {
        runtimeRouteRecords.delete(m.record);
        untrackRecord(m.record);
      }
    }

    nav.clearCaches();

    return () => {
      remove();
      for (const record of addedRecords) {
        runtimeRouteRecords.delete(record);
      }
      nav.clearCaches();
    };
  }

  function removeRoute(name: RouteRecordName) {
    const recordMatcher = matcher.getRecordMatcher(name);
    if (recordMatcher) {
      matcher.removeRoute(recordMatcher);
      forEachInTree(recordMatcher, (m) => {
        runtimeRouteRecords.delete(m.record);
        untrackRecord(m.record);
      });
      nav.clearCaches();
    } else if (__DEV__) {
      warn(`Cannot remove non-existent route "${String(name)}"`);
    }
  }

  function clearRoutes() {
    matcher.clearRoutes();
    allowResolverOnlyRecords = false;
    activeGeneratedRouteNames.clear();
    activeGeneratedRoutePaths.clear();
    runtimeRouteRecords.clear();
    nav.clearCaches();
  }

  function replaceRoutes(routes: Readonly<RouteRecordRaw[]>) {
    clearRoutes();
    for (const route of routes) {
      matcher.addRoute(route);
    }
    for (const m of matcher.getRoutes()) {
      trackRecord(m.record);
    }
  }

  const go = (delta: number) => routerHistory.go(delta);

  // --- Lifecycle (init / destroy) ---
  // Absorbed from the former lifecycle.ts. The router manages its own
  // initialization and cleanup directly — no callback indirection needed.

  let started: boolean | undefined;
  let activeViewCount = 0;
  let removeHistoryListener: undefined | null | (() => void);

  function setupHistoryListener() {
    if (removeHistoryListener) return;

    removeHistoryListener = routerHistory.listen((to, _from, info) => {
      if (!router.listening) return;

      const toLocation = nav.resolve(to) as RouteLocationNormalized;
      const shouldRedirect = nav.handleRedirectRecord(toLocation);
      if (shouldRedirect) {
        // Save the scroll position of the page we are leaving before bailing
        // out to the redirect. Without this, a pop that lands on a redirecting
        // record loses the scroll position for the origin entry.
        if (isBrowser) {
          scrollPositionStore.save(
            getScrollKey(currentRoute.value.fullPath, info.delta),
            computeScrollPosition(),
          );
        }
        nav.pushWithRedirect(assign({}, shouldRedirect, { replace: true }), toLocation).catch(noop);
        return;
      }

      nav.setPendingLocation(toLocation);
      const from = currentRoute.value;
      if (isBrowser) {
        scrollPositionStore.save(getScrollKey(from.fullPath, info.delta), computeScrollPosition());
      }

      nav
        .runGuardPipeline(toLocation, from)
        .catch((error: NavigationFailure | NavigationRedirectError) => {
          if (
            isNavigationFailure(
              error,
              ErrorTypes.NAVIGATION_ABORTED | ErrorTypes.NAVIGATION_CANCELLED,
            )
          ) {
            return error;
          }

          if (isNavigationFailure(error, ErrorTypes.NAVIGATION_GUARD_REDIRECT)) {
            nav
              .pushWithRedirect((error as NavigationRedirectError).to, toLocation)
              .then((failure) => {
                if (
                  isNavigationFailure(
                    failure,
                    ErrorTypes.NAVIGATION_ABORTED | ErrorTypes.NAVIGATION_DUPLICATED,
                  ) &&
                  !info.delta &&
                  info.type === NavigationType.pop
                ) {
                  routerHistory.go(-1, false);
                }
              })
              .catch(noop);
            return Promise.reject();
          }

          if (info.delta) {
            routerHistory.go(-info.delta, false);
          }
          return nav.triggerError(error, toLocation, from);
        })
        .then(async (failure: NavigationFailure | void) => {
          failure =
            failure ||
            nav.finalizeNavigation(
              toLocation as RouteLocationNormalizedLoaded,
              from,
              false,
              false,
              undefined,
              info.delta,
            );

          if (!failure) {
            await nextTick();
          }

          if (failure) {
            if (info.delta && !isNavigationFailure(failure, ErrorTypes.NAVIGATION_CANCELLED)) {
              routerHistory.go(-info.delta, false);
            } else if (
              info.type === NavigationType.pop &&
              isNavigationFailure(
                failure,
                ErrorTypes.NAVIGATION_ABORTED | ErrorTypes.NAVIGATION_DUPLICATED,
              )
            ) {
              routerHistory.go(-1, false);
            }
          }

          nav.triggerAfterEach(toLocation as RouteLocationNormalizedLoaded, from, failure);
        })
        .catch(noop);
    });
  }

  function init() {
    activeViewCount++;
    if (activeViewCount > 1) return;

    const shouldPerformInitialNavigation =
      isBrowser && !started && toRaw(currentRoute.value) === START_LOCATION_NORMALIZED;

    if (shouldPerformInitialNavigation) {
      started = true;
      nav.pushWithRedirect(routerHistory.location).catch((error: unknown) => {
        if (__DEV__) warn('Unexpected error when starting the router:', error);
      });
    }
    provide(routerKey, router);
    provide(routeLocationKey, routeLocationContext);
    provide(routerViewLocationKey, currentRoute);
  }

  function destroy() {
    if (activeViewCount > 0) {
      activeViewCount--;
    }
    if (activeViewCount > 0) {
      return;
    }

    nav.setPendingLocation(START_LOCATION_NORMALIZED);

    if (removeHistoryListener) {
      removeHistoryListener();
      removeHistoryListener = null;
    }

    try {
      currentRoute.value = START_LOCATION_NORMALIZED;
    } catch (error) {
      if (__DEV__) {
        warn('Failed to reset current route during destroy:', error);
      }
    }
    nav.clearCaches();
    scrollPositionStore.clear();
    started = false;
    nav.setReady(false);
    // Re-arm the history listener for a potential re-init (the router is
    // reusable: `started` is reset above). `onFirstReady` is one-shot and was
    // already consumed on the first ready, so without this a remounted
    // RouterView would never react to browser back/forward again.
    nav.onFirstReady(setupHistoryListener);
    unregisterActiveRouter(router);
  }

  nav.onFirstReady(setupHistoryListener);

  // --- Build the router object ---
  const router = {
    currentRoute,
    listening: true,
    options,

    // Route management
    addRoute: addRoute as Router['addRoute'],
    removeRoute,
    clearRoutes,
    hasRoute: (name: RouteRecordName) => !!matcher.getRecordMatcher(name),
    getRoutes: () => matcher.getRoutes().map((m) => m.record),

    // Resolution & navigation
    resolve: nav.resolve as Router['resolve'],
    push: nav.push as Router['push'],
    replace: nav.replace as Router['replace'],
    preloadRoute: nav.preloadRoute as Router['preloadRoute'],
    go,
    back: () => go(-1),
    forward: () => go(1),

    // Guards
    beforeEach: nav.beforeGuards.add,
    beforeResolve: nav.beforeResolveGuards.add,
    afterEach: nav.afterGuards.add,

    // Lifecycle
    onError: nav.onError,
    isReady: nav.isReady,
    init,
    destroy,

    // Prerender
    getPrerenderPaths: () => collectPrerenderPaths(matcher.getRoutes().map((r) => r.record)),
    getPrerenderPathsAsync: () =>
      collectPrerenderPathsAsync(matcher.getRoutes().map((r) => r.record)),
    getRouteRenderMode: (name: RouteRecordName): RouteRenderMode => {
      const record = matcher.getRecordMatcher(name)?.record;
      if (record?.start?.prerender) return 'prerender';
      if (record?.start?.ssr) return 'ssr';
      return 'csr';
    },
    _hmrReplaceResolver(nextResolver: FixedRouteResolver) {
      activeResolver = nextResolver;
      nav.clearCaches();
    },
    _hmrReplaceRoutes: replaceRoutes,
  } satisfies _RouterInternal;

  registerActiveRouter(router);

  return router;
}

// ---------------------------------------------------------------------------
// Prerender path collection
// ---------------------------------------------------------------------------

type PrerenderRecord = { name?: RouteRecordName; path: string; meta: any; start?: any };

function collectPrerenderPaths(records: PrerenderRecord[]): PrerenderPathInfo[] {
  return records
    .filter((r) => r.start?.prerender)
    .flatMap((record) => {
      const paths = resolvePrerenderPaths(record, false) as string[];
      return paths.length > 0
        ? [{ name: record.name, pathTemplate: record.path, paths, meta: record.meta || {} }]
        : [];
    });
}

async function collectPrerenderPathsAsync(
  records: PrerenderRecord[],
): Promise<PrerenderPathInfo[]> {
  const collected: PrerenderPathInfo[] = [];
  for (const record of records) {
    if (!record.start?.prerender) continue;
    const paths = await resolvePrerenderPaths(record, true);
    if (paths.length > 0) {
      collected.push({
        name: record.name,
        pathTemplate: record.path,
        paths,
        meta: record.meta || {},
      });
    }
  }
  return collected;
}

/**
 * Unified prerender path resolver. When `allowAsync` is false, async
 * `prerenderPaths` functions emit a dev warning and return `[]`.
 */
function resolvePrerenderPaths(
  record: { path: string; start?: any },
  allowAsync: true,
): Promise<string[]> | string[];
function resolvePrerenderPaths(record: { path: string; start?: any }, allowAsync: false): string[];
function resolvePrerenderPaths(
  record: { path: string; start?: any },
  allowAsync: boolean,
): Promise<string[]> | string[] {
  const configured = record.start?.prerenderPaths;

  if (configured) {
    if (isFunction(configured)) {
      const result = configured();
      if (result instanceof Promise) {
        if (allowAsync) return result;
        if (__DEV__) {
          warn(
            `Dynamic prerender route "${record.path}" returned an async "start.prerenderPaths". Use "getPrerenderPathsAsync()" to resolve it.`,
          );
        }
        return [];
      }
      return result;
    }
    return configured;
  }

  // Static routes produce their own path; dynamic routes need explicit config
  if (record.path.includes(':')) {
    if (__DEV__) {
      warn(
        `Dynamic prerender route "${record.path}" requires "start.prerenderPaths" to provide concrete output paths.`,
      );
    }
    return [];
  }

  return [record.path];
}
